version: 0.2
env:
  parameter-store:
    IMAGE_NAME_WEB: "image_name_web"
    IMAGE_NAME_DB: "image_name_db"
    AWS_DEFAULT_REGION: "default_region"
    AWS_ACCOUNT_ID: "account_id"
    DOCKERHUB_PASSWORD: "dockerhub_password"
    DOCKERHUB_USERNAME: "dcokerhub_username"
phases:
  install:
    runtime-versions:
      docker: 20
  
  pre_build:
    commands:
      - echo Logging in to Dockerhub...
      - echo "${DOCKERHUB_PASSWORD}" | docker login -u "${DOCKERHUB_USERNAME}" --password-stdin  
      - echo Logging in to Amazon ECR...
      - aws ecr get-login-password --region $AWS_DEFAULT_REGION | docker login --username AWS --password-stdin $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com
      - echo Pulling latest images...
      - docker pull $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/$IMAGE_NAME_WEB:latest
      - docker pull $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/$IMAGE_NAME_DB:latest
  build:
    commands:
      - echo Build started on `date` 
      - echo Building the Docker images ...
      - docker-compose build
      - docker-compose up -d
      - echo Attaching a tag to image ...
      - docker tag $IMAGE_NAME_WEB $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/$IMAGE_NAME_WEB:latest
      - docker tag $IMAGE_NAME_DB $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/$IMAGE_NAME_DB:latest
  
  post_build:
    commands:
      - echo Build completed on `date`
      - echo Pushing the Docker image ...
      - echo Pushing app ...
      - docker push $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/$IMAGE_NAME_WEB:latest
      - echo Pushing db ...
      - docker push $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/$IMAGE_NAME_DB:latest
      - echo Writing image definitions file...
      - printf '[{"name":"web","imageUri":"%s"}]' $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/$IMAGE_NAME_WEB:latest > web_imagedefinitions.json
      - printf '[{"name":"postgres","imageUri":"%s"}]' $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/$IMAGE_NAME_DB:latest > db_imagedefinitions.json
artifacts:
  files: 
    - web_imagedefinitions.json
    - db_imagedefinitions.json