version: 0.2
env:
  parameter-store:
    IMAGE_REPO_NAME_APP: "image_repo_name_app"
    IMAGE_REPO_NAME_DB: "image_repo_name_db"
    AWS_DEFAULT_REGION: "default_region"
    AWS_ACCOUNT_ID: "account_id"
phases:
  install:
    runtime-versions:
      docker: 20
  
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - aws ecr get-login-password --region $AWS_DEFAULT_REGION | docker login --username AWS --password-stdin $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com
      # - docker login -u AWS -p $(aws ecr get-login-password --region $AWS_DEFAULT_REGION) $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com
  build:
    commands:
      - echo Build started on 'date' 
      - echo Building the Docker images ...
      - docker-compose up -d
      - echo Attaching a tag to image ...
      - docker tag $IMAGE_REPO_NAME_APP $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/deploy_app/$IMAGE_REPO_NAME_APP:latest
      - docker tag $IMAGE_REPO_NAME_DB $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/deploy_app/$IMAGE_REPO_NAME_DB:latest
  
  post_build:
    commands:
      - echo Build completed on 'date'
      - echo Pushing the Docker image ...
      - echo Pushing app ...
      - docker push $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/deploy_app/$IMAGE_REPO_NAME_APP:latest
      - echo Pushing db ...
      - docker push $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/deploy_app/$IMAGE_REPO_NAME_DB:latest